"""14.11.2024

Revision ID: 791d0b8a98b9
Revises: 3f2cef8ca312
Create Date: 2024-11-14 12:37:45.691520

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "791d0b8a98b9"
down_revision: Union[str, None] = "3f2cef8ca312"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "matches", "winner_id", existing_type=mysql.INTEGER(), nullable=True
    )
    op.alter_column(
        "matches", "score", existing_type=mysql.JSON(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "matches", "score", existing_type=mysql.JSON(), nullable=False
    )
    op.alter_column(
        "matches", "winner_id", existing_type=mysql.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
