"""4444

Revision ID: 97ac6912bd82
Revises: 
Create Date: 2024-10-16 23:21:32.432969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97ac6912bd82'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.CHAR(length=36), nullable=False),
    sa.Column('player1', sa.Integer(), nullable=False),
    sa.Column('player2', sa.Integer(), nullable=False),
    sa.Column('winner', sa.Integer(), nullable=False),
    sa.Column('score', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['player1'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player2'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'uuid'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    op.drop_table('players')
    # ### end Alembic commands ###
